manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/joelspadin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: send-string-behavior
      import: app/west.yml
  self:
    path: config
